# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

bolero_check_results <- function(steps, rows, nsteps_) {
    invisible(.Call(`_dance_bolero_check_results`, steps, rows, nsteps_))
}

bolero_lgl_steps_to_indices <- function(steps, n_steps_, original_rows) {
    .Call(`_dance_bolero_lgl_steps_to_indices`, steps, n_steps_, original_rows)
}

salsa_check_sizes <- function(steps, rows, n_formulas_) {
    invisible(.Call(`_dance_salsa_check_sizes`, steps, rows, n_formulas_))
}

